//! Segmentation against a PDF a real word processor produced.
//!
//! Six successive attempts at the page-boundary rule shipped a silent defect,
//! and every one of them passed the unit fixtures. The fixtures were the
//! problem: they hand-build `ConvertedDocument`, so they encode what the author
//! believed `pdf_extract` emits. Real output differs in ways that decided every
//! one of those bugs -- LibreOffice draws the running header and footer FIRST
//! in the content stream, a running footer is the last thing on the page for
//! other producers, and a clause that wraps a page has the furniture sitting
//! between its two halves.
//!
//! The fixture is a synthetic contract generated by LibreOffice Writer from a
//! .docx carrying genuine `w:hdr`/`w:ftr` parts and a real PAGE field. It
//! contains no client material.

use minutes_archive_convert::{convert_bytes, SourceFormat, PDF_UNSUPPORTED_STRUCTURE_WARNING};
use minutes_archive_core::retrieval::{
    normalize_converted_document, CurrentRevisionSet, DocumentId, LegalConcept, LegalIndex,
    LegalQuery, MatchScope, ProvisionBoundaries, VaultId,
};

const LIABILITY_WRAP: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/liability-wrap.pdf");

#[test]
fn a_real_pdf_keeps_a_wrapped_cap_with_its_carve_out_and_furniture_out_of_the_body() {
    let converted = convert_bytes(SourceFormat::Pdf, LIABILITY_WRAP).expect("convert");
    assert!(
        converted.blocks.len() >= 2,
        "fixture must span pages to exercise the boundary; got {} block(s)",
        converted.blocks.len()
    );

    let normalized = normalize_converted_document(
        DocumentId::parse("real-liability").expect("id"),
        "Real Liability",
        LIABILITY_WRAP,
        &converted,
    )
    .expect("normalize");

    // The cap and the carve-out that limits it are one clause in the document
    // and must be one provision in the index. Severing them let the cap be
    // quoted to counsel without the exception that guts it.
    let cap = normalized
        .provisions
        .iter()
        .find(|provision| provision.text.contains("shall not be liable to the other"))
        .expect("the liability cap is indexed");
    assert!(
        cap.text
            .contains("shall not apply to a breach of the confidentiality"),
        "the carve-out was severed from the cap it limits:\n{}",
        cap.text
    );

    // Running furniture belongs to the page, not to the clause. In the body it
    // fabricates concept matches and lends the clause its sentence count.
    for provision in &normalized.provisions {
        let is_clause = provision.text.contains("shall not be liable to the other")
            || provision.text.contains("Recipient shall protect");
        if is_clause {
            assert!(
                !provision.text.contains("MASTER SERVICES AGREEMENT"),
                "the running header was welded into a clause body:\n{}",
                provision.text
            );
        }
    }

    // Every extracted line survives somewhere. Deleting furniture once erased
    // real carve-outs, so the index must never lose a line it was given.
    // A caption is stored in `heading`, not in `text`, so both count as
    // indexed -- `searchable_text` covers the pair.
    let indexed = normalized
        .provisions
        .iter()
        .map(|provision| {
            format!(
                "{} {}",
                provision.heading.as_deref().unwrap_or_default(),
                provision.text
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let source_text = converted
        .blocks
        .iter()
        .map(|block| block.text.as_str())
        .collect::<Vec<_>>()
        .join("\n");
    let occurrences = |haystack: &str, needle: &str| {
        let haystack = haystack.split_whitespace().collect::<Vec<_>>();
        let needle = needle.split_whitespace().collect::<Vec<_>>();
        haystack
            .windows(needle.len())
            .filter(|window| *window == needle)
            .count()
    };
    for block in &converted.blocks {
        for line in block.text.lines().map(str::trim).filter(|l| !l.is_empty()) {
            assert!(
                indexed.contains(line),
                "a line the converter produced is not in the index: {line:?}"
            );
            let input_count = occurrences(&source_text, line);
            let output_count = occurrences(&indexed, line);
            assert!(
                output_count >= input_count,
                "line occurrence count decreased for {line:?}: {input_count} -> {output_count}"
            );
        }
    }
}

const LIST_TAIL_MERGE: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/list-tail-merge.pdf");
const UNIFORM_SPACING_CAPTIONS: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/uniform-spacing-captions.pdf");
const DOUBLE_SPACED_SIGNATURE: &[u8] =
    include_bytes!("../../../tests/fixtures/archive-real-pdf/double-spaced-signature.pdf");

/// Reproduces the open defect in #26 against real LibreOffice output.
///
/// The page ends mid-list on an unterminated item and the next page opens an
/// unrelated Assignment clause under a title-case caption that no lexical rule
/// recognises, in a document with one uniform font size -- so no word-level
/// rule can see either caption. The two clauses are indexed as one provision,
/// and a same-provision query for confidentiality and assignment returns a
/// card claiming a conjunction the document does not contain.
#[test]
fn a_real_pdf_does_not_fabricate_a_same_provision_conjunction() {
    let converted = convert_bytes(SourceFormat::Pdf, LIST_TAIL_MERGE).expect("convert");
    let normalized = normalize_converted_document(
        DocumentId::parse("list-tail-merge").expect("id"),
        "List Tail Merge",
        LIST_TAIL_MERGE,
        &converted,
    )
    .expect("normalize");

    for provision in &normalized.provisions {
        let carries_confidentiality = provision.text.contains("Confidential Information");
        let carries_assignment = provision.text.contains("may assign");
        assert!(
            !(carries_confidentiality && carries_assignment),
            "one provision now spans two unrelated clauses:\n{}",
            provision.text
        );
    }
}

/// This fixture used to be unsegmentable and was withheld from same-provision
/// search entirely. Its captions carry no size change, no indentation and no
/// numbering -- the only signal is that a caption is preceded by a wider gap
/// than the line spacing inside a paragraph.
///
/// The reference for "wider" used to be the median gap in the document, which
/// is the paragraph gap whenever most paragraphs are a single line, as they
/// are here. The threshold then sat above every gap in the document and no
/// break could be found. Anchoring it to font size instead recovers the
/// captions, because line spacing is proportional to type size while a
/// document statistic is not.
///
/// What must not change is the refusal to invent a conjunction: the
/// confidentiality clause and the assignment clause are still separate
/// provisions, and a same-provision query must not join them.
#[test]
fn a_real_pdf_with_uniform_type_recovers_its_captions_without_fabricating_a_conjunction() {
    let converted = convert_bytes(SourceFormat::Pdf, UNIFORM_SPACING_CAPTIONS).expect("convert");
    assert!(
        !converted
            .warnings
            .iter()
            .any(|warning| warning == PDF_UNSUPPORTED_STRUCTURE_WARNING),
        "uniform-type captions are recoverable from line spacing; got {:?}",
        converted.warnings
    );

    let normalized = normalize_converted_document(
        DocumentId::parse("uniform-spacing-captions").expect("id"),
        "Uniform Spacing Captions",
        UNIFORM_SPACING_CAPTIONS,
        &converted,
    )
    .expect("normalize");
    assert_eq!(
        normalized.provision_boundaries,
        ProvisionBoundaries::Declared,
        "captions were recovered, so boundaries are no longer inferred"
    );

    // The point of recovering the captions is that the clauses separate. If
    // they ever merge again, this fixture is back to fabricating the exact
    // conjunction #26 was raised for.
    for provision in &normalized.provisions {
        let carries_confidentiality = provision.text.contains("Confidential Information");
        let carries_assignment = provision.text.contains("may assign");
        assert!(
            !(carries_confidentiality && carries_assignment),
            "one provision now spans two unrelated clauses:\n{}",
            provision.text
        );
    }
    assert!(
        normalized.provisions.len() >= 3,
        "expected the three captioned clauses to separate; got {}",
        normalized.provisions.len()
    );
    let revisions = CurrentRevisionSet::from_documents([&normalized]);
    let mut index =
        LegalIndex::new(VaultId::parse("fixture-vault").expect("vault")).expect("index");
    index.replace_document(&normalized).expect("ingest");

    let exact = LegalQuery {
        raw: "remember the exact phrase".to_string(),
        scope: MatchScope::AnywhereInDocument,
        required_concepts: Vec::new(),
        excluded_concepts: Vec::new(),
        exact_phrase: Some("Confidential Information".to_string()),
        max_sentences: None,
        limit: 10,
    };
    let exact_response = index
        .search(index.vault_id(), exact, &revisions)
        .expect("exact phrase");
    assert_eq!(exact_response.documents.len(), 1);

    let document_scope = LegalQuery {
        raw: "find documents containing confidentiality and assignment".to_string(),
        scope: MatchScope::AnywhereInDocument,
        required_concepts: vec![LegalConcept::Confidentiality, LegalConcept::Assignment],
        excluded_concepts: Vec::new(),
        exact_phrase: None,
        max_sentences: None,
        limit: 10,
    };
    let document_response = index
        .search(index.vault_id(), document_scope, &revisions)
        .expect("document conjunction");
    assert_eq!(document_response.documents.len(), 1);

    let same_provision = LegalQuery {
        raw: "find a confidentiality provision containing assignment".to_string(),
        scope: MatchScope::SameProvision,
        required_concepts: vec![LegalConcept::Confidentiality, LegalConcept::Assignment],
        excluded_concepts: Vec::new(),
        exact_phrase: None,
        max_sentences: None,
        limit: 10,
    };
    let same_response = index
        .search(index.vault_id(), same_provision, &revisions)
        .expect("same provision");
    // Empty for the right reason now. The clauses are separate provisions, so
    // there is no conjunction to return -- rather than the old outcome, where
    // the answer was withheld because the boundaries could not be trusted.
    assert!(same_response.evidence.is_empty());
    assert_eq!(
        same_response.inferred_boundary_evidence_withdrawn, 0,
        "nothing should be withheld once the boundaries are declared"
    );
}

/// The counterpart to the uniform-type fixture, and the reason a caption has
/// to introduce something rather than merely follow a wide gap.
///
/// This document is double spaced, so its ordinary paragraph gap is far wider
/// than its line spacing -- wide enough that any gap-only rule marks every
/// paragraph as a caption. Its signature block is a run of short title-case
/// paragraphs ("Northwind Holdings International Limited", "By: Jane Ellis",
/// "Title: Managing Director") which satisfy every word-level test a caption
/// does. Marking them splits one signature block into six provisions and
/// invites a same-provision match across two different signatories.
///
/// What separates them is what follows: a caption is followed by prose, a
/// signature line by another short line.
#[test]
fn a_double_spaced_signature_block_is_not_a_run_of_captions() {
    let converted = convert_bytes(SourceFormat::Pdf, DOUBLE_SPACED_SIGNATURE).expect("convert");

    for block in &converted.blocks {
        let text = block.text.trim();
        assert!(
            !(block.is_heading == Some(true)
                && (text.starts_with("By:")
                    || text.starts_with("Title:")
                    || text.ends_with("Limited")
                    || text.ends_with("Incorporated"))),
            "a signature-block line was marked as a caption: {text}"
        );
    }

    // The real captions in the same document must survive the rule that
    // rejects the signature block, or this test would pass by detecting
    // nothing at all.
    assert!(
        converted
            .blocks
            .iter()
            .any(|block| block.is_heading == Some(true)
                && block.text.contains("Assignment and Change of Control")),
        "the rule rejected the signature block by rejecting every caption too"
    );

    let normalized = normalize_converted_document(
        DocumentId::parse("double-spaced-signature").expect("id"),
        "Double Spaced Signature",
        DOUBLE_SPACED_SIGNATURE,
        &converted,
    )
    .expect("normalize");
    for provision in &normalized.provisions {
        let signatories = ["Jane Ellis", "Peter Nakamura"]
            .iter()
            .filter(|name| provision.text.contains(**name))
            .count();
        assert!(
            signatories <= 1 || provision.text.contains("Signed for and on behalf"),
            "two signatories were merged into one provision:\n{}",
            provision.text
        );
    }
}
